---
title: "293 Project Simulations"
author: "Jason"
date: '2022-04-10'
output: pdf_document
---

```{r setup, include=FALSE}
library("designmatch")
library("ggplot2")
library("mvtnorm")
library("Matrix")
```

Pre-treat = c(“x1...)
Cobalt::bal.tab(x = df[,pre-treat], treat = df$y, continuous = “std”)
Library(Matching)


Simulation Parameters:

```{r}
samp_data <- function(seed=293, sampsize=100, paramrep=3){
  # This function extends the feature matrix according to Hainmueller (2012)
  # Where every set of 6 columns is generated in the same way as Hainmueller
  # PARAMETERS:
  # seed: sets the seed for the random generator
  # sampsize: the sample size generated by the function
  # paramrep: sets the number of repeated sets of 6 generated by the sample data

  # sets the random seed
  set.seed(seed)
  
  # generates MVN covariance matrix for Hainmueller (2012)
  sigmainit <- matrix(c(2, 1, -1, 1, 1, -0.5, -1, -0.5, 1), ncol=3, nrow=3)
  temp <- lapply(seq_len(paramrep), function(X) sigmainit)
  sigmamatrix <- bdiag(temp)
  
  # as.matrix is needed because bdiag is a sparse matrix
  m_norm <- rmvnorm(sampsize, mean = rep(0, paramrep*3), sigma = as.matrix(sigmamatrix))
  
  # generates uniform, chi-squared, and binomial data
  m_unif <- matrix(runif(sampsize*paramrep, min=-3, max=3), nrow=sampsize, ncol=paramrep)
  m_chisq <- matrix(rchisq(sampsize*paramrep, df=1), nrow=sampsize, ncol=paramrep)
  m_binom <- matrix(rbinom(sampsize*paramrep, size=1, prob=0.5), nrow=sampsize, ncol=paramrep)
  
  # returns the dataset
  return(data.frame(cbind(m_norm, m_unif, m_chisq, m_binom)))
}
```

For timing:
```{r}
start_time <- Sys.time()

end_time <- Sys.time()
end_time - start_time
```




Designmatch Example:
```{r}
data("lalonde", package = "designmatch")
covs = c("age", "education", "black", "hispanic", "married", "nodegree", "re74",
"re75")
mom_targets = colMeans(lalonde[, covs])
cov_sds = apply(lalonde[, covs], 2, sd)
mom_tols = 0.05 * cov_sds

t_ind = lalonde$treatment
mom_covs = as.matrix(lalonde[, covs])
mom = list(covs = mom_covs, tols = mom_tols, targets = mom_targets)

# Solver:

t_max = 60*30
solver = "gurobi"
approximate = 0
solver = list(name = solver, t_max = t_max, approximate = approximate, round_cplex = 0, trace = 0)

## Performing profile matching
pmatch_out = profmatch(t_ind, mom, solver)
## Selecting the units that are matched
lalonde_matched = lalonde[pmatch_out$id,]
```


